version: '3.8'
services:
  cassandra:
    # this version is currently the latest,
    image: cassandra:4.1.6
    container_name: cassandra
    ports:
      - "9042:9042" # client connections using the Cassandra Query Language (CQL) protocol
      - "7000:7000" # internal communication between Cassandra nodes in cassandra.yaml
      - "7001:7001" # internal communication nodes over SSL/TLS if configured in cassandra.yaml
      - "7199:7199" # Java Management Extensions (JMX) Monitoring and Management in cassandra-env.sh
    # a small number of environment variable supported to update configs inside 'cassandra.yaml'
    # https://github.com/docker-library/docs/tree/master/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME='Cassandra Cluster'
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - cassandra_net
volumes:
  cassandra_data:
    driver: local
networks:
  cassandra_net:
    driver: bridge