version: '3.8'
services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "8080:8080"  # NiFi Web UI
    environment:
      - NIFI_WEB_HTTP_PORT=8080
    volumes:
      - nifi_data:/opt/nifi/nifi-current/data
      - nifi_conf:/opt/nifi/nifi-current/conf
    networks:
      - nifi-network
volumes:
  nifi_data:
    driver: local
  nifi_conf:
    driver: local
networks:
  nifi-network:
    driver: bridge