version: '3.8'

services:
  cassandra:
    image: cassandra:5.0.0
    container_name: cassandra
    restart: unless-stopped
    volumes:
      - cassandra_data:/var/lib/cassandra
    ports:
      - "9042:9042"
    networks:
      - cassandra

volumes:
  cassandra_data:
    name: cassandra_data
    driver: local

networks:
  cassandra:
    name: cassandra
    driver: bridge