version: '3.8'

services:
  elasticsearch:
    image: localhost/elasticsearch:8.5.1
    container_name: elasticsearch
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "19076:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - es_logs:/usr/share/elasticsearch/logs
    networks:
      - elk

volumes:
  es_data:
    name: es_data
    driver: local
  es_logs:
    name: es_logs
    driver: local

networks:
  elk:
    name: elk
    driver: bridge
