version: '3.8'

services:

  keycloak:
    image: bitnami/keycloak:25.0.6
    container_name: keycloak
    restart: unless-stopped
    environment:
      KEYCLOAK_HTTP_PORT: 8080
      KEYCLOAK_HTTPS_PORT: 8443

      KEYCLOAK_ENABLE_STATISTICS: true
      KEYCLOAK_ENABLE_HEALTH_ENDPOINTS: true

      KEYCLOAK_DATABASE_HOST: "db"
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: keycloak

      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "12345678@Ab"
    ports:
      - "8070:8080"
    depends_on:
      - db
    networks:
      - keycloak

  db:
    image: postgres:16.4
    container_name: keycloak_db
    restart: unless-stopped
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    networks:
      - keycloak

volumes:
  keycloak_postgres_data:
    name: keycloak_postgres_data
    driver: local

networks:
  keycloak:
    name: keycloak
    driver: bridge