version: '3.8'

services:
  mongodb:
    image: mongo:8.0.0
    container_name: mongodb
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongo

volumes:
  mongo_data:
    name: mongo_data
    driver: local

networks:
  mongo:
    name: mongo
    driver: bridge