version: '3.8'

services:
  postgres:
    image: postgres:16.4
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    name: postgres_data
    driver: local