version: '3.8'

services:
  sonarqube:
    image: sonarqube:9.9.1-community
    container_name: sonarqube
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - sonarqube

  db:
    image: postgres:16.4
    container_name: sonarqube_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    ports:
      - "5432:5432"
    volumes:
      - sonarqube_postgresql:/var/lib/postgresql
      - sonarqube_postgresql_data:/var/lib/postgresql/data
    networks:
      - sonarqube

volumes:
  sonarqube_postgresql:
    name: sonarqube_postgresql
    driver: local
  sonarqube_postgresql_data:
    name: sonarqube_postgresql_data
    driver: local
  sonarqube_conf:
    name: sonarqube_conf
    driver: local
  sonarqube_data:
    name: sonarqube_data
    driver: local
  sonarqube_logs:
    name: sonarqube_logs
    driver: local
  sonarqube_extensions:
    name: sonarqube_extensions
    driver: local

networks:
  sonarqube:
    name: sonarqube
    driver: bridge